version: '3.5'

services:
  emqx:
    image: emqx/emqx:5.0.9
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      - ${NETWORK_NAME}
